### PR TITLE
Got rid of Base64Util and Base64UtilTest in favor of the existing Base64.

### PR DESCRIPTION
**Pull request by sanjay-saxena**

### CODE REVIEW

**Comment by jitsni** [comment]
I suggest just use JDK's 
http://docs.oracle.com/javase/7/docs/api/javax/xml/bind/DatatypeConverter.html#printBase64Binary(byte[])

**Comment by jfallows** [comment]
Needs to support Java6 for Android.

On Saturday, January 17, 2015, Jitendra Kotamraju notifications@github.com
wrote:

> I suggest just use JDK's
> 
> http://docs.oracle.com/javase/7/docs/api/javax/xml/bind/DatatypeConverter.html#printBase64Binary(byte[])
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kaazing/netx.http/pull/6#issuecomment-70386971.

## 

_John Fallows_
CTO\*  |  _Phone: +1.650.960.8148  |  Mobile: +1.415.215.6597
*----------------------------------------------------------------------_
KAAZING >|<
Event-Driven Communication. Fast. Secure. Mobile. Guaranteed.
Kaazing.com http://www.kaazing.com/  |  Download
http://kaazing.com/download.html  |  Blog http://blog.kaazing.com/  |
Twitter https://twitter.com/kaazing

**Comment by jitsni** [comment]
It is there in Java SE 6, don't know about android.

**Comment by jfallows** [comment]
Java6 has a Base64 API as part of the XML support.

http://docs.oracle.com/javase/6/docs/api/javax/xml/bind/DatatypeConverter.html#printBase64Binary(byte[])

Android has it's own Base64 API.

http://developer.android.com/reference/android/util/Base64.html

Java8 has a dedicated Base64 API.

http://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

We need our Java Base64 code to span both Java6+ (Android) and Java7+ (JRE).

Our options appear to be to write our own code, or use reflection to re-use
the platform-specific APIs.

When our base platform becomes Java8 (even on Android) then we could use
java.util.Base64.

On Sat, Jan 17, 2015 at 7:05 PM, Jitendra Kotamraju <
notifications@github.com> wrote:

> It is there in Java SE 6, don't know about android.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaazing/netx.http/pull/6#issuecomment-70394660>.
>



-- 

*John Fallows*
CTO*  |  *Phone: +1.650.960.8148  |  Mobile: +1.415.215.6597
*----------------------------------------------------------------------*
KAAZING >|<
Event-Driven Communication. Fast. Secure. Mobile. Guaranteed.
Kaazing.com <http://www.kaazing.com/>  |  Download
<http://kaazing.com/download.html>  |  Blog <http://blog.kaazing.com/>  |
Twitter <https://twitter.com/kaazing>

**Comment by jfallows** [comment]
Java6 has a Base64 API as part of the XML support.

[javax.xml.bind.DatatypeConverter.html#printBase64Binary(byte[])](http://docs.oracle.com/javase/6/docs/api/javax/xml/bind/DatatypeConverter.html#printBase64Binary%28byte[]%29)

Android has it's own Base64 API.

[android.util.Base64](http://developer.android.com/reference/android/util/Base64.html)

Java8 has a new Base64 API in the core packages.

[java.util.Base64](http://docs.oracle.com/javase/8/docs/api/java/util/Base64.html)

We need our Java Base64 code to span both Java6+ (Android) and Java7+ (JRE).

Our options appear to be to write our own code, or use reflection to re-use
the platform-specific APIs.

When our base platform becomes Java8 (even on Android) then we could use
`java.util.Base64`.

**Pull request merged**
